## Python Inheritance

#### Python Class

In [1]:
class Car():
    def __init__(self, windows, doors, enginetype):
        self.windows=windows
        self.doors=doors
        self.enginetype=enginetype
    
    def drive(self):
        print("The person drives the car")

In [2]:
car = Car(4, 5, "CNG")
car.drive()

The person drives the car


#### Python Class Inheritance

In [3]:
class audi(Car):
    def __init__(self, windows, doors, enginetype, supportsai):
        super().__init__(windows, doors, enginetype)
        self.supportsai=supportsai
        
    def selfdrive(self):
        print("The person drives self driving Audi")

In [4]:
audiQ7=audi(4,5,"CNG", True)

In [5]:
dir(audiQ7)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'doors',
 'drive',
 'enginetype',
 'selfdrive',
 'supportsai',
 'windows']

In [6]:
audiQ7.selfdrive()

The person drives self driving Audi


#### Magic Methods In Classes

In [7]:
class Car():
    def __init__(self, windows, doors, enginetype):
        self.windows=windows
        self.doors=doors
        self.enginetype=enginetype
    
    def drive(self):
        print("The person drives the car")

In [8]:
c = Car(4, 5, "LPG")
print(c)

In [9]:
c

In [10]:
dir(c)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'doors',
 'drive',
 'enginetype',
 'windows']

##### overwrite some methods like __str__, __sizeof__, __new__

In [11]:
class Car():
    
    def __new__(self, windows, doors, enginetype):
        return "object started"
    
    def __init__(self, windows, doors, enginetype):
        self.windows=windows
        self.doors=doors
        self.enginetype=enginetype
    def __str__(self):
        return "Object initialized"
    
    def __sizeof__(self):
        return "object size"
    
    def drive(self):
        print("The person drives the car")

In [12]:
c = Car(4, 5, "LPG")
print(c)

object started


In [13]:
c.__sizeof__()

63

In [14]:
c.__str__()

'object started'

#### Multiple Class Inheritance in Python

In [15]:
class A:
    def method1(self):
        print("A class method is called")
        

class B(A):
    def method1(self):
        print("B class method is called")
    def method2(self):
        print("B class method2 is called")
        
class C(A):
    def method1(self):
        print("C class method is called")
        
class D(B,C):
    def method1(self):
        print("D class method is called")
        C.method1(self)
        B.method1(self)
        A.method1(self)

In [16]:
d=D()
d.method1()

D class method is called
C class method is called
B class method is called
A class method is called


another way of calling individually could be

In [17]:
B.method1(d)

B class method is called


In [18]:
A.method1(d)

A class method is called


## Class Methods And Class variables

In [19]:
class Car:
    base_price=100000 ##Class Variables
    def __init__(self,windows,doors,power):
        self.windows=windows
        self.doors=doors
        self.power=power
    def what_base_price(self):
        print(f"The base price is {self.base_price}")

In [20]:
car1=Car(8, 5, 4000)

In [21]:
car1.what_base_price()

The base price is 100000


In [22]:
class Car:
    base_price=100000 ##Class Variables
    def __init__(self,windows,doors,power):
        self.windows=windows
        self.doors=doors
        self.power=power
    def what_base_price(self):
        print("The base price is {}".format(self.base_price))
    @classmethod
    def revise_base_price(cls,inflation):
        cls.base_price=cls.base_price+cls.base_price*inflation

In [23]:
car2=Car(8,5,4000)
car2.what_base_price()

The base price is 100000


In [24]:
car2.revise_base_price(0.12)

In [25]:
car2.base_price#updating the value
#even when we change the instance, we get the base price value updated

112000.0

In [26]:
car3=Car(8,5,2000)
car3.what_base_price()

The base price is 112000.0


## Static Method

In [27]:
year=2020

In [28]:
class Car:
    base_price=100000 ##Class Variables
    def __init__(self,windows,doors,power):
        self.windows=windows
        self.doors=doors
        self.power=power
    def what_base_price(self):
        print("The base price is {}".format(self.base_price))
    @classmethod
    def revise_base_price(cls,inflation):
        cls.base_price=cls.base_price+cls.base_price*inflation
    @staticmethod
    def check_year():
        if year == 2020:
            return True
        else:
            return False

In [29]:
car4=Car(8,5,2000)

In [30]:
car4.check_year()

True

In [31]:
if(car4.check_year()):
    pass
else:
    car4.revise_base_price(0.12)

In [32]:
car4.base_price

100000

## Exception Handling in Python

#### Errors cannot be handled, while Python exceptions can be handled at the run time. Error might indicate critical problems that a reasonable application should not try to catch, while an Exception might indicate conditions that an application should try to catch.

In [33]:
try:
    a=int(input("Enter an integer: "))
    b=int(input("Enter an integer: "))
    c=a*b
    d=a+b
    e=a/b
    
except NameError:
    print("Variable not defined")
except ZeroDivisionError:
    print("Provide a num gretaer than 0")
except TypeError:
    print("Input data type as integer")
except Exception as ex:
    print(ex)
        
else:
    print(c)
    print(d)
    print(e)
finally:
    print("The code has been executed")

Enter an integer: 10
Enter an integer: 15.5
invalid literal for int() with base 10: '15.5'
The code has been executed


In [34]:
try:
    a=int(input("Enter an integer: "))
    b=int(input("Enter an integer: "))
    c=a*b
    d=a+b
    e=a/b
    
except NameError:
    print("Variable not defined")
except ZeroDivisionError:
    print("Provide a num gretaer than 0")
except TypeError:
    print("Input data type as integer")
except Exception as ex:
    print(ex)
        
else:
    print(c)
    print(d)
    print(e)
finally:
    print("The code has been executed")

Enter an integer: 10
Enter an integer: 15
150
25
0.6666666666666666
The code has been executed


#### Custom Exception

In [35]:
class Error(Exception):
    pass

class DoBError(Error):
    pass

In [36]:
year =int(input("Enter the age: "))
age=2021-year
try:
    if age<=30 & age>=20:
        print("You can apply")
    else:
        raise DoBError
except DoBError:
    print("You can't apply")

Enter the age: 1984
You can't apply


In [37]:
year =int(input("Enter the age: "))
age=2021-year
try:
    if age<=30 & age>=20:
        print("You can apply")
    else:
        raise DoBError
except DoBError:
    print("You can't apply")

Enter the age: 1995
You can apply


## Python Generators vs Iterators

#### Iterator

In [38]:
##iterable
lst=[1,2,3,4]
for i in lst:
    print(i)

1
2
3
4


In [39]:
##iterator
iterable=iter(lst)
type(iterable)

list_iterator

In [40]:
## We can iterate
for i in iterable:
    print(i)

1
2
3
4


In [41]:
try:
    print(next(iterable))
except StopIteration:
    print("The iterator is empty")

The iterator is empty


#### Generator

In [42]:
### Generator
def square(n):
    for i in range(n):
        yield i**2
        
for i in square(3):
    print(i)

0
1
4


In [43]:
a=square(3)
a

<generator object square at 0x0000017545BB0890>

In [44]:
next(a)

0

#### Difference b/w Iterator and Generator

1. To create iterator we use iter() and to generator we use function along with yield keyword\
2. Generator uses the yield keyword. It saves the local variable\
3. Generator in python helps us top write fast and compact code\
4. Python iterator is much more memory efficient

In [45]:
import types,collections
issubclass(types.GeneratorType,collections.Iterator)

<ipython-input-45-5715e0adaa13>:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  issubclass(types.GeneratorType,collections.Iterator)


True

## Python Decorators

In [46]:
def welcome():
    return "Kenny Omega is the best wrestler in the world."

wel=welcome()
del welcome

In [47]:
wel

'Kenny Omega is the best wrestler in the world.'

Even though the function is removed, since we have copied the function to another variable, it retains the function value

In [48]:
### Closures
def main_welcome(message):
    
    def sub_welcome_class():
        print("Welcome to my humble aboard!")
        print(message)
        print("Please have a seat")
    return sub_welcome_class()


main_welcome(message="Kenny Omega")

Welcome to my humble aboard!
Kenny Omega
Please have a seat


**Clsoures**: In closures, we can write a parent function, define sub-functions that will be accessible.

In [49]:
### Closures & initial Decorators
def main_welcome(func):
   
    def sub_welcome_class():
        print("Welcome to my humble aboard!")
        print(func([1]))
        print("Please have a seat Evil Uno of Dark Order")
    return sub_welcome_class()

main_welcome(len)

Welcome to my humble aboard!
1
Please have a seat Evil Uno of Dark Order


**Decorators**: Calling functions within a function and can also call the function as input parameter

In [50]:
### Decorators
def main_welcome(func):
    def sub_welcome_class():
        print("Welcome to my humble aboard!")
        print("Please have a seat Evil Uno of Dark Order")
    return sub_welcome_class()

In [51]:
def dark_order_num():
    print("This is Evil Uno of Dark Order")

In [52]:
main_welcome(dark_order_num())

This is Evil Uno of Dark Order
Welcome to my humble aboard!
Please have a seat Evil Uno of Dark Order


#### Or,

In [53]:
@main_welcome
def dark_order_num():
    print("This is Evil Uno of Dark Order")

Welcome to my humble aboard!
Please have a seat Evil Uno of Dark Order


## IS vs ==

In [54]:
ls1=[1,2,3]
ls2=[1,2,3]
ls1==ls2

True

In [55]:
ls3=[1,2,3]
ls4=[1,2,4]
ls3==ls4

False

here both are assigned at different memory locations.

In [56]:
ls1=[1,2,3]
ls2=[1,2,3]
ls1 is ls2

False

In [57]:
ls5=[1,2,3]
ls6=ls5
ls5 is ls6

True

In [58]:
ls6 is ls5

True

here, only a single memory location is assigned. Mutalbility is also possible.

In [59]:
ls6[1]=8
ls6

[1, 8, 3]

In [60]:
ls5

[1, 8, 3]

here if an element is changed in any list, it'll also change for another list 

**Note**: In pandas with.copy(), we create another memeory location 

In [61]:
import numpy as np
x=np.array([1,2,3])
x#np.array creates an array

array([1, 2, 3])

In [62]:
y=np.asarray([1,2,3])
y#asarray() converts input to an array

array([1, 2, 3])

In [63]:
z=np.asarray(["Divyansh", 25, "GP"])
z

array(['Divyansh', '25', 'GP'], dtype='<U8')

**np.array() by default will make a copy of the object, while np.asarray() will not. So, mutablity is possible for np.asarray()**

In [64]:
np.array(x)[1]=8

In [65]:
x

array([1, 2, 3])

In [66]:
np.asarray(x)[1]=8
x

array([1, 8, 3])